# Generated by Django 5.0.2 on 2024-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yeardb",
            name="bth",
            field=models.DateField(),
        ),
    ]
