# Generated by Django 5.0.3 on 2024-03-22 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_book_daydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='bookID',
            field=models.CharField(default='bookID', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterID', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.book')),
            ],
        ),
    ]
