# Generated by Django 5.0.3 on 2024-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_book_author_book_bookid_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=20, unique=True, verbose_name='帳號')),
                ('Password', models.CharField(max_length=20, verbose_name='密碼')),
            ],
            options={
                'verbose_name_plural': '帳號',
                'ordering': ('Email',),
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('bookname',), 'verbose_name_plural': '書籍'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('title',), 'verbose_name_plural': '章節名稱'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=10, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.CharField(default='bookID', max_length=20, unique=True, verbose_name='編號'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=20, verbose_name='書名'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapterID',
            field=models.CharField(max_length=20, unique=True, verbose_name='章節編號'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.TextField(default='content', verbose_name='內文'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=50, verbose_name='章節名稱'),
        ),
    ]
