# Generated by Django 5.0.3 on 2024-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_customer_alter_book_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Name',
            field=models.CharField(default='u want me call u something', max_length=20, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(default='Email', max_length=20, unique=True, verbose_name='帳號'),
        ),
    ]
