# Generated by Django 5.0.2 on 2024-04-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_chatmessage1_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage1',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
