# Generated by Django 5.0.2 on 2024-04-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_chatmessage2_delete_chatmessage1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
