# Generated by Django 5.0.2 on 2024-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_conversation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bth', models.DateField()),
            ],
        ),
    ]
