# Generated by Django 5.0.2 on 2024-05-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='birthday',
        ),
    ]
