# Generated by Django 5.0.2 on 2024-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='birthday_time',
            field=models.TextField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='birthday',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
