# Generated by Django 5.0.2 on 2024-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_birthday_birthday_time_alter_birthday_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='birthday_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
