# Generated by Django 5.0.2 on 2024-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_alter_birthday_birthday_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='sex2',
            field=models.CharField(default='無', max_length=1),
        ),
    ]
