# Generated by Django 5.0.6 on 2024-05-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_birthday_sex2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='sex2',
            field=models.CharField(max_length=1),
        ),
    ]
