# Generated by Django 5.0.6 on 2024-05-31 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_alter_birthday_sex2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('january', models.TextField(blank=True, null=True)),
                ('february', models.TextField(blank=True, null=True)),
                ('march', models.TextField(blank=True, null=True)),
                ('april', models.TextField(blank=True, null=True)),
                ('may', models.TextField(blank=True, null=True)),
                ('june', models.TextField(blank=True, null=True)),
                ('july', models.TextField(blank=True, null=True)),
                ('august', models.TextField(blank=True, null=True)),
                ('september', models.TextField(blank=True, null=True)),
                ('october', models.TextField(blank=True, null=True)),
                ('november', models.TextField(blank=True, null=True)),
                ('december', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
