# Generated by Django 5.0.6 on 2024-06-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_yearly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yeardb',
        ),
    ]
