# Generated by Django 5.0.6 on 2024-06-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_delete_yeardb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='daydb',
        ),
        migrations.DeleteModel(
            name='ChatMessage2',
        ),
    ]
