# Generated by Django 5.0.6 on 2024-06-03 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_remove_chatmessage2_user_delete_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Birthday',
            new_name='Customer',
        ),
    ]
