# Generated by Django 5.0.6 on 2024-06-03 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_rename_birthday_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sex2',
            new_name='sex',
        ),
    ]
